name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt update
        apt-cache search pylint
        sudo apt-get install -y --fix-missing libgirepository1.0-dev libgtk-3-0 python3-guestfs python3-gi python3-psutil pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
